name: CI

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}
      - uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Setup poetry
        run: curl -sSL https://install.python-poetry.org | python - && export PATH="$PATH:$HOME/.poetry/bin"
      - name: Install dependencies
        run: poetry config virtualenvs.in-project true && poetry install
      - uses: pre-commit/action@v2.0.3
      - name: Run pytest
        run: poetry run pytest -v --cov=src
